# Generated by Django 6.0 on 2026-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_mode',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
