# Generated by Django 6.0 on 2026-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile_current_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
